export const dairyProducts = [
    {
        id: 1,
        name: "Amul Shakti Fresh Milk",
        image: "/images/amul-shakti.jpg",
        quantity: "500 ml",
        price: 31,
    },
    {
        id: 2,
        name: "Amul Gold Full Cream Milk",
        image: "/images/amul-gold.jpg",
        quantity: "500 ml",
        price: 34,
    },
    {
        id: 3,
        name: "Moreish Classic White Bread",
        image: "/images/white-bread.jpg",
        quantity: "400 g",
        price: 45,
    },
    {
        id: 4,
        name: "Moreish Brown Bread",
        image: "/images/brown-bread.jpg",
        quantity: "400 g",
        price: 50,
    },
    {
        id: 5,
        name: "Amul Salted Butter",
        image: "/images/amul-butter.jpg",
        quantity: "100 g",
        price: 62,
    },
    {
        id: 6,
        name: "Sudha Dairy Shakti Fresh Milk",
        image: "/images/sudha-milk.jpg",
        quantity: "500 ml",
        price: 30,
    },
    {
        id: 7,
        name: "Cool Eggs - 12 pcs",
        image: "/images/cool-eggs.jpg",
        quantity: "12 pcs",
        price: 99,
        discount: "40% OFF"
    },
    {
        id: 8,
        name: "Sudha Dairy Fresh Butter",
        image: "/images/sudha-butter.jpg",
        quantity: "100 g",
        price: 55,
    },
    {
        id: 9,
        name: "Moreish Fresh Cream",
        image: "/images/moreish-cream.jpg",
        quantity: "200 ml",
        price: 70,
    },
    {
        id: 10,
        name: "Amul Cheese Slices",
        image: "/images/amul-cheese.jpg",
        quantity: "200 g",
        price: 120,
    },
    {
        id: 11,
        name: "Sudha Dairy Ghee",
        image: "/images/sudha-ghee.jpg",
        quantity: "500 g",
        price: 450,
    },
    {
        id: 12,
        name: "Moreish Fresh Paneer",
        image: "/images/moreish-paneer.jpg",
        quantity: "200 g",
        price: 80,
    },
    {
        id: 13,
        name: "Amul Fresh Curd",
        image: "/images/amul-curd.jpg",
        quantity: "200 g",
        price: 25,
    },
    {
        id: 14,
        name: "Sudha Dairy Fresh Lassi",
        image: "/images/sudha-lassi.jpg",
        quantity: "200 ml",
        price: 30,
    },
    {
        id: 15,
        name: "Moreish Fresh Yogurt",
        image: "/images/moreish-yogurt.jpg",
        quantity: "200 g",
        price: 35,
    },
    {
        id: 16,
        name: "Amul Fresh Butter Milk",
        image: "/images/amul-butter-milk.jpg",
        quantity: "200 ml",
        price: 20,
    },
    {
        id: 17,
        name: "Sudha Dairy Fresh Ice Cream",
        image: "/images/sudha-ice-cream.jpg",
        quantity: "500 ml",
        price: 150,
    },
    {
        id: 18,
        name: "Moreish Fresh Cheese Spread",
        image: "/images/moreish-cheese-spread.jpg",
        quantity: "200 g",
        price: 90,
    },
    {
        id: 19,
        name: "Amul Fresh Cream Cheese",
        image: "/images/amul-cream-cheese.jpg",
        quantity: "200 g",
        price: 110,
    },
    {
        id: 20,
        name: "Sudha Dairy Fresh Tofu",
        image: "/images/sudha-tofu.jpg",
        quantity: "200 g",
        price: 75,
    },
    {
        id: 21,
        name: "Moreish Fresh Mozzarella",
        image: "/images/moreish-mozzarella.jpg",
        quantity: "200 g",
        price: 95,
    },
    {
        id: 22,
        name: "Amul Fresh Ricotta Cheese",
        image: "/images/amul-ricotta.jpg",
        quantity: "200 g",
        price: 100,
    },
    {
        id: 23,
        name: "Sudha Dairy Fresh Kefir",
        image: "/images/sudha-kefir.jpg",
        quantity: "200 ml",
        price: 40,
    },
    {
        id: 24,
        name: "Moreish Fresh Labneh",
        image: "/images/moreish-labneh.jpg",
        quantity: "200 g",
        price: 85,
    },
    {
        id: 25,
        name: "Amul Fresh Butter Spread",
        image: "/images/amul-butter-spread.jpg",
        quantity: "200 g",
        price: 65,
    },
    {
        id: 26,
        name: "Sudha Dairy Fresh Cream Cheese",
        image: "/images/sudha-cream-cheese.jpg",
        quantity: "200 g",
        price: 120,
    },
    {
        id: 27,
        name: "Moreish Fresh Sour Cream",
        image: "/images/moreish-sour-cream.jpg",
        quantity: "200 g",
        price: 75,
    },
    {
        id: 28,
        name: "Amul Fresh Whipped Cream",
        image: "/images/amul-whipped-cream.jpg",
        quantity: "200 ml",
        price: 80,
    },
    {
        id: 29,
        name: "Sudha Dairy Fresh Butter Milk Powder",
        image: "/images/sudha-butter-milk-powder.jpg",
        quantity: "200 g",
        price: 60,
    },
    {
        id: 30,
        name: "Moreish Fresh Cheese Cubes",
        image: "/images/moreish-cheese-cubes.jpg",
        quantity: "200 g",
        price: 100,
    },
];
